version: '3'

services:
  mysql:
    container_name: bbdd-empresa-sql
    image: mysql:latest
    ports:
      - "3306:3306"    
    volumes:
      - mysql-dato:/var/lib/mysql
      - ../backup/bbdd_empresa.sql:/var/lib/mysql/bbdd_empresa.sql:ro
    env_file: mysql.env
    command: mysql -u root -p $MYSQL_ROOT_PASSWORD --default-character-set=utf8 -D empresa < /var/lib/mysql/bbdd_empresa.sql -f
    restart: unless-stopped
  web:
    container_name: candidatos
    image: app-candidatos:3.0.0
    build:
      context: .
      dockerfile: candidatos.Dockerfile
      target: app
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    volumes:
      - webapp-datos:/usr/local/tomcat/webapps/gestion-candidatos/fotos
    env_file: web.env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    
volumes:
  mysql-dato:
  webapp-datos:
