apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-data
  namespace: acme
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi