apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: acme-candidatos
  namespace: acme
spec: 
  selector:
    matchLabels:
      app: acme-candidatos
  replicas: 1 
  template:
    metadata:
      name: acme-webapp
      namespace: acme
      labels:
        app: acme-candidatos
    spec:
      affinity:
        podAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - mysql
                topologyKey: "kubernetes.io/hostname"
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - acme-candidatos
              topologyKey: "kubernetes.io/hostname"
      initContainers:
        - name: init-java-compilation
          image: maven:3.6.3-jdk-11
          envFrom:
            - secretRef:
                name: acme-candidatos
          env:
            - name: REPO_GITHUB
              valueFrom:
                configMapKeyRef:
                  name: acme-app-candidatos
                  key: REPO_GITHUB
            - name: DB_URL
              valueFrom:
                configMapKeyRef:
                  name: acme-app-candidatos
                  key: DB_URL
            - name: DB_DRIVER
              valueFrom:
                configMapKeyRef:
                  name: acme-app-candidatos
                  key: DB_DRIVER
          volumeMounts:
            - name: java-compilation
              mountPath: /app_java_temp
            - name: scripts
              readOnly: true
              mountPath: /scripts
          workingDir: /app_java_temp
          command: ['sh', "/scripts/bootstrap.sh"]
        - name: init-carga-datos-sql
          image: mysql:latest
          envFrom:
            - configMapRef:
                name: acme-app-candidatos
            - secretRef:
                name: acme-candidatos
          volumeMounts:
            - name: sql-schema
              readOnly: true
              mountPath: /mysql
          workingDir: /mysql
          command: [ "sh", "-c", "mysql -u$DB_USER -p$DB_PASS -h $DB_SERVER -P $DB_PORT --default-character-set=$CHARACTER_SET -D $BBDD < $PATH_BBDD -f" ]
      containers:
        - name: javaee
          image: tomcat:9.0-jdk11-temurin-focal
          envFrom:
            - configMapRef:
                name: acme-app-candidatos
            - secretRef:
                name: acme-candidatos
          volumeMounts:
            - name: java-compilation
              mountPath: /usr/local/tomcat/webapps/gestion-candidatos
              subPath: deploy
            - name: webapp-data
              mountPath: /usr/local/tomcat/webapps/gestion-candidatos/fotos
          workingDir: /usr/local/tomcat/webapps/gestion-candidatos
          command: [ "sh", "-c", "jar -xvf gestion-candidatos.war && catalina.sh run" ]
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 350m
            limits:
              cpu: 450m
          livenessProbe:
            httpGet:
              path: /gestion-candidatos
              port: 8080
              httpHeaders:
                - name: Liveness-probe-http
                  value: "true"
            initialDelaySeconds: 40
            periodSeconds: 90
            timeoutSeconds: 10
            failureThreshold: 3
            successThreshold: 1
      volumes:
        - name: java-compilation
          emptyDir: {}
        - name: webapp-data
          gcePersistentDisk:
            pdName: acme-fotos-candidatos
        - name: sql-schema
          configMap: 
            name: acme-bbdd-empresa
        - name: scripts
          configMap:
            name:  acme-scripts
      restartPolicy: Always